// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-bkuRTcSi6c8Z54R_H5I0Fzd-Spm8Fs',
    appId: '1:899288628231:web:15cd16e6737d825f99fea2',
    messagingSenderId: '899288628231',
    projectId: 'ecfile-test',
    authDomain: 'ecfile-test.firebaseapp.com',
    storageBucket: 'ecfile-test.appspot.com',
    measurementId: 'G-1P8WHC2G0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKq102-TrnILyMz9Dl1euij2jad_Pi58',
    appId: '1:899288628231:android:cc83514759d0a63099fea2',
    messagingSenderId: '899288628231',
    projectId: 'ecfile-test',
    storageBucket: 'ecfile-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfZtUA-x0EFXzBt-XVVq_jiIRBaFii7xM',
    appId: '1:899288628231:ios:b78b91c91537f1b399fea2',
    messagingSenderId: '899288628231',
    projectId: 'ecfile-test',
    storageBucket: 'ecfile-test.appspot.com',
    androidClientId: '899288628231-5j49jatpcoidu3p8il72hp3u0kmji07u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfZtUA-x0EFXzBt-XVVq_jiIRBaFii7xM',
    appId: '1:899288628231:ios:77ba5e32f3558c3799fea2',
    messagingSenderId: '899288628231',
    projectId: 'ecfile-test',
    storageBucket: 'ecfile-test.appspot.com',
    androidClientId: '899288628231-5j49jatpcoidu3p8il72hp3u0kmji07u.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
